name: NPM Package Auto-publisher

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: "16.9.1"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check that the secret is set
        env:
          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          if [[ -z "$TOKEN" ]]; then
            echo '::error::The secret API_TOKEN_GITHUB must be set.'
            exit 1
          fi

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@itcig'

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: yarn publish
